apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: aia-backend
  namespace: paw
  labels:
    team: paw
  annotations:
    config.linkerd.io/proxy-memory-limit: 512Mi
    config.linkerd.io/proxy-memory-request: 128Mi
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  image: {{image}}
  port: 3000
  azure:
    application:
      enabled: true
  liveness:
    path: /aia-backend/internal/isAlive
    initialDelay: 10
  readiness:
    path: /aia-backend/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: false
  replicas:
    min: 2
    max: 4
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  webproxy: true
  ingresses:
    - https://www.nav.no/aia-backend
  envFrom:
    - secret: aia-backend-unleash-api-token
  env:
    - name: BASE_PATH
      value: /aia-backend
    - name: CORS_ALLOWED_ORIGINS
      value: www.nav.no
    - name: CORS_ALLOWED_SCHEMES
      value: https
    - name: VEILARBDIALOG_API_URL
      value: http://veilarbdialog.dab/veilarbdialog/api
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging.prod-fss-pub.nais.io
    - name: VEILARBVEDTAKINFO_URL
      value: https://veilarbvedtakinfo.prod-fss-pub.nais.io
    - name: BESVARELSE_URL
      value: http://paw-arbeidssoker-besvarelse
    - name: SSO_NAV_COOKIE
      value: sso-nav.no
    - name: UNLEASH_SERVER_API_URL
      value: https://paw-unleash-api.nav.cloud.nais.io/api
    - name: OPPGAVE_URL
      value: https://oppgave.prod-fss-pub.nais.io
    - name: OPPGAVE_API_SCOPE
      value: api://prod-fss.oppgavehandtering.oppgave/.default
    - name: ARBEIDSSOKERREGISTERET_OPPSLAG_API_URL
      value: http://paw-arbeidssoekerregisteret-api-oppslag
    - name: ARBEIDSSOKERREGISTERET_INNGANG_API_URL
      value: http://paw-arbeidssokerregisteret-api-inngang
    - name: PAW_MICROFRONTEND_TOGGLER_URL
      value: http://paw-microfrontend-toggler
    - name: BEKREFTELSE_API_URL
      value: http://paw-arbeidssoekerregisteret-api-bekreftelse
    - name: PAW_TILGANGSKONTROLL_API_URL
      value: http://paw-tilgangskontroll
  resources:
    limits:
      cpu: "3"
      memory: 1536Mi
    requests:
      cpu: 100m
      memory: 580Mi
  accessPolicy:
    inbound:
      rules:
        - application: arbeidssokerregistrering
        - application: arbeidssokerregistrering-for-veileder
        - application: arbeidssoekerregisteret-for-personbruker
        - application: tms-min-side-proxy
          namespace: min-side
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: prod-fss
        - application: veilarbvedtaksstotte
          namespace: obo
          cluster: prod-gcp
        - application: veilarbperson
          namespace: obo
          cluster: prod-gcp
    outbound:
      external:
        - host: veilarboppfolging.prod-fss-pub.nais.io
        - host: veilarbvedtakinfo.prod-fss-pub.nais.io
        - host: paw-unleash-api.nav.cloud.nais.io
        - host: oppgave.prod-fss-pub.nais.io
      rules:
        - application: paw-arbeidssoekerregisteret-api-oppslag
        - application: paw-arbeidssokerregisteret-api-inngang
        - application: paw-microfrontend-toggler
        - application: paw-arbeidssoekerregisteret-api-bekreftelse
        - application: paw-tilgangskontroll
        - application: veilarbdialog
          namespace: dab
          cluster: prod-gcp
        - application: paw-arbeidssoker-besvarelse
        - application: veilarboppfolging
          namespace: poao
          cluster: prod-gcp
        - application: veilarbvedtakinfo
          namespace: pto
          cluster: prod-fss
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - name: aia-backend
  kafka:
    pool: nav-prod
