apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: aia-backend-unleash
  namespace: paw
  labels:
    "team": "paw"
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: paw
  secretName: aia-backend-unleash-api-token
  environment: production
