apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: aia-backend
  namespace: paw
  labels:
    team: paw
spec:
  image: {{image}}
  port: 3000
  azure:
    application:
      enabled: true
  liveness:
    path: /aia-backend/internal/isAlive
    initialDelay: 10
  readiness:
    path: /aia-backend/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /aia-backend/internal/prometheus
  replicas:
    min: 1
    max: 1
  tokenx:
    enabled: true
  idporten:
    enabled: true
  ingresses:
    - https://www.intern.dev.nav.no/aia-backend
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: BASE_PATH
      value: /aia-backend
    - name: CORS_ALLOWED_ORIGINS
      value: www.dev.nav.no
    - name: CORS_ALLOWED_SCHEMES
      value: https
    - name: MELDEKORT_APP_NAME
      value: meldekort-api-q1
    - name: MELDEKORT_URL
      value: http://meldekort-api-q1.meldekort.svc.cluster.local/meldekort/meldekort-api/api/person
    - name: PTO_PROXY_URL
      value: https://pto-proxy.dev.intern.nav.no/proxy
    - name: VEILARBDIALOG_API_URL
      value: https://veilarbdialog.dev-fss-pub.nais.io/veilarbdialog/api
    - name: DIALOG_APP_NAME
      value: veilarbdialog
    - name: VEILARBREGISTRERING_URL
      value: http://veilarbregistrering
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging.dev-fss-pub.nais.io
    - name: VEILARBVEDTAKINFO_URL
      value: https://veilarbvedtakinfo.dev-fss-pub.nais.io
    - name: UNLEASH_API_URL
      value: https://unleash.nais.io/api/
    - name: UNLEASH_ENVIRONMENT
      value: dev
    - name: DAGPENGER_INNSYN_URL
      value: http://dp-innsyn.teamdagpenger.svc.cluster.local
    - name: KAFKA_TOPIC
      value: paw.arbeidssoker-reaktivering-v1
    - name: SITUASJON_URL
      value: https://arbeidssoker-situasjon.intern.dev.nav.no
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: 500m
      memory: 580Mi
  accessPolicy:
    inbound:
      rules:
        - application: veientilarbeid
        - application: paw-reaktiver-arbeidssoker
        - application: tms-min-side-proxy
          namespace: min-side
    outbound:
      external:
        - host: veilarboppfolging.dev-fss-pub.nais.io
      rules:
        - application: dp-innsyn
          namespace: teamdagpenger
        - application: meldekort-api-q1
          namespace: meldekort
        - application: veilarbdialog
          namespace: pto
          cluster: dev-fss
        - application: veilarbregistrering
        - application: paw-arbeidssoker-situasjon
        - application: veilarboppfolging
          namespace: pto
          cluster: dev-fss
        - application: veilarbvedtakinfo
          namespace: pto
          cluster: dev-fss
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: aia-backend
  kafka:
    pool: nav-dev
