apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: aia-backend
  namespace: paw
  labels:
    team: paw
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  image: {{image}}
  port: 3000
  azure:
    application:
      enabled: true
      allowAllUsers: true
  liveness:
    path: /aia-backend/internal/isAlive
    initialDelay: 10
  readiness:
    path: /aia-backend/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /aia-backend/internal/prometheus
  replicas:
    min: 1
    max: 1
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  ingresses:
    - https://www.ansatt.dev.nav.no/aia-backend
    - https://www.intern.dev.nav.no/aia-backend
  envFrom:
    - secret: aia-backend-unleash-api-token
  env:
    - name: BASE_PATH
      value: /aia-backend
    - name: CORS_ALLOWED_ORIGINS
      value: www.dev.nav.no
    - name: CORS_ALLOWED_SCHEMES
      value: https
    - name: MELDEKORT_APP_NAME
      value: meldekort-api-q1
    - name: MELDEKORT_URL
      value: http://meldekort-api-q1.meldekort.svc.cluster.local/meldekort/meldekort-api/api/person
    - name: VEILARBDIALOG_API_URL
      value: http://veilarbdialog.dab/veilarbdialog/api
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging.dev-fss-pub.nais.io
    - name: VEILARBVEDTAKINFO_URL
      value: https://veilarbvedtakinfo.dev-fss-pub.nais.io
    - name: SSO_NAV_COOKIE
      value: sso-dev-nav.no
    - name: UNLEASH_SERVER_API_URL
      value: https://paw-unleash-api.nav.cloud.nais.io/api
    - name: OPPGAVE_URL
      value: https://oppgave-q1.dev-fss-pub.nais.io
    - name: OPPGAVE_API_SCOPE
      value: api://dev-fss.oppgavehandtering.oppgave-q1/.default
    - name: ARBEIDSSOKERREGISTERET_OPPSLAG_API_URL
      value: http://paw-arbeidssoekerregisteret-api-oppslag
    - name: ARBEIDSSOKERREGISTERET_INNGANG_API_URL
      value: http://paw-arbeidssokerregisteret-api-inngang
    - name: PAW_MICROFRONTEND_TOGGLER_URL
      value: http://paw-microfrontend-toggler
    - name: BEKREFTELSE_API_URL
      value: http://paw-arbeidssoekerregisteret-api-bekreftelse
    - name: PAW_TILGANGSKONTROLL_API_URL
      value: http://paw-tilgangskontroll
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
  accessPolicy:
    inbound:
      rules:
        - application: arbeidssokerregistrering
        - application: arbeidssokerregistrering-for-veileder
        - application: arbeidssoekerregisteret-for-personbruker
        - application: tms-min-side-proxy
          namespace: min-side
        - application: veilarbvedtaksstotte
          namespace: obo
        - application: tokenx-token-generator
          namespace: nais
        - application: azure-token-generator
          namespace: nais
    outbound:
      external:
        - host: veilarboppfolging.dev-fss-pub.nais.io
        - host: veilarbvedtakinfo.dev-fss-pub.nais.io
        - host: paw-unleash-api.nav.cloud.nais.io
        - host: oppgave-q1.dev-fss-pub.nais.io
      rules:
        - application: paw-arbeidssoekerregisteret-api-oppslag
        - application: paw-arbeidssokerregisteret-api-inngang
        - application: paw-microfrontend-toggler
        - application: paw-arbeidssoekerregisteret-api-bekreftelse
        - application: paw-tilgangskontroll
        - application: veilarbdialog
          namespace: dab
          cluster: dev-gcp
        - application: veilarboppfolging
          namespace: poao
          cluster: dev-gcp
        - application: veilarbvedtakinfo
          namespace: pto
          cluster: dev-fss
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-f1-micro
        databases:
          - name: aia-backend
  kafka:
    pool: nav-dev
