name: Build, push, and deploy

on:
    push:
        branches:
            - main
            - dev/*

jobs:
#    set-vars:
#        name: Setter vars
#        runs-on: ubuntu-latest
#        outputs:
#            tag: ${{ steps.tag.outputs.tag }}
#            image: ${{ env.IMAGE_BASE }}:${{ steps.tag.outputs.tag }}
#        steps:
#            - name: Checkout
#              uses: actions/checkout@v3
#
#            - name: Lag tag for image
#              id: tag
#              run: echo "tag=$(git log -1 --pretty='%ad_%h' --date=format:'%Y%m%d%H%M%S')" >> ${GITHUB_OUTPUT}

    build:
        name: Test, build and push
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: docker-build-push
              uses: nais/docker-build-push@v0
              id: docker-build-push
              with:
                team: paw
                identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
        outputs:
          image: ${{ steps.docker-build-push.outputs.image }}


    deploy-dev:
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev')
        name: Deploy til dev
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Deploy
              uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  IMAGE: ${{ needs.build.outputs.image }}
                  RESOURCE: nais/dev-gcp/nais.yaml

    deploy-prod:
        if: github.ref == 'refs/heads/main'
        name: Deploy til prod
        needs: [build, deploy-dev]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Deploy
              uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: nais/prod-gcp/nais.yaml
                  IMAGE: ${{ needs.build.outputs.image }}
                  DRY_RUN: false
#
#    release:
#        if: github.ref == 'refs/heads/main'
#        name: Tag and release
#        needs: [set-vars, deploy-prod]
#        runs-on: ubuntu-latest
#        steps:
#            - name: Checkout
#              uses: actions/checkout@v3
#
#            - name: Create release
#              uses: actions/create-release@v1
#              env:
#                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#              with:
#                  tag_name: release/prod@${{ needs.set-vars.outputs.tag }}
#                  release_name: Release ${{ needs.set-vars.outputs.tag }} to prod
#                  prerelease: false
