name: Build, push, and deploy

on:
    push:
        branches:
            - main
            - dev/*

jobs:
    build:
        name: Test, build and push
        permissions:
          contents: "read"
          id-token: "write"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: docker-build-push
              uses: nais/docker-build-push@v0
              id: docker-build-push
              with:
                team: paw
                identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
        outputs:
          image: ${{ steps.docker-build-push.outputs.image }}


    deploy-dev:
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev')
        name: Deploy til dev
        permissions:
          contents: "read"
          id-token: "write"
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Deploy
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: dev-gcp
                  IMAGE: ${{ needs.build.outputs.image }}
                  RESOURCE: nais/dev-gcp/nais.yaml

    deploy-prod:
        if: github.ref == 'refs/heads/main'
        name: Deploy til prod
        permissions:
          contents: "read"
          id-token: "write"
        needs: [build, deploy-dev]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Deploy
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: prod-gcp
                  RESOURCE: nais/prod-gcp/nais.yaml
                  IMAGE: ${{ needs.build.outputs.image }}
                  DRY_RUN: false

    apply-apitoken-unleash:
      name: Legger til ApiToken for Unleash
      permissions:
        contents: "read"
        id-token: "write"
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: deploy to dev
          uses: nais/deploy/actions/deploy@v2
          env:
            CLUSTER: dev-gcp
            RESOURCE: nais/dev-gcp/unleash-apitoken.yaml
        - name: deploy to prod
          uses: nais/deploy/actions/deploy@v2
          env:
            CLUSTER: prod-gcp
            RESOURCE: nais/prod-gcp/unleash-apitoken.yaml
